# -----------------------------------------
# Site Configuration & Basic Metadata
# -----------------------------------------
title: "Rodrigo Sgarbi | Developer & Problem Solver"
description: "Showcasing my professional background, selected projects, and technical expertise. Connect with me to learn more or collaborate."
lang: en
layout: sidebar
style: light

# -----------------------------------------
# URL & Permalinks
# -----------------------------------------
permalink: /:year/:month/:day/:title/

# -----------------------------------------
# Plugins
# -----------------------------------------
plugins:
  - jekyll-seo-tag         # Provides SEO tags (e.g., Open Graph, Twitter Cards)
  - jekyll-sitemap         # Generates a sitemap.xml for search engines
  - jekyll-feed            # Adds an RSS feed for your posts
  - jekyll-github-metadata # Grabs GitHub data for project list
  - jemoji                 # Allows GitHub-flavored emoji
  - jekyll-octicons        # GitHub Octicons for icons in Markdown

# -----------------------------------------
# Defaults (for posts, pages, etc.)
# -----------------------------------------
defaults:
  - scope:
      path: ""    # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# -----------------------------------------
# Personal / Author Information
# -----------------------------------------
author:
  name: "Rodrigo Sgarbi"
  email: "sgarbi.rodrigo@gmail.com"
  url: "https://sgarbirodrigo.github.io" # or your LinkedIn URL
  # Additional fields (optional):
  headline: "Full-Stack Developer | Submarine Officer | Naval Science | Python"
  company: "Brazilian Navy Full Stack Developer"
  location: "Rio de Janeiro, Brazil"

# -----------------------------------------
# Open Graph & Social Media
# -----------------------------------------
# (Used by jekyll-seo-tag, LinkedIn, Twitter, and other platforms)
social:
  name: "Rodrigo Sgarbi"
  links:
    - "https://linkedin.com/in/rodrigosgarbi"
    - "https://github.com/sgarbirodrigo"
    #- "https://twitter.com/your-twitter-username"
    # Add or remove as needed

# -----------------------------------------
# Projects Configuration
# -----------------------------------------
projects:
  sort_by: pushed          # sort_by options: [pushed, stars]
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      # - repo-name

# -----------------------------------------
# Topics Section
# -----------------------------------------
topics:
  - name: Django
    web_url: https://github.com/topics/django
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/django/django.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/python/python.png

  - name: Bootstrap
    web_url: https://github.com/topics/bootstrap
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/bootstrap/bootstrap.png

# -----------------------------------------
# Additional SEO & Build Options
# -----------------------------------------
# Enable GitHub Pages' recommended markdown processor
markdown: kramdown
kramdown:
  input: GFM

# If you have verification codes for search engines, you can add them here:
# google_site_verification: "YOUR_GOOGLE_VERIFICATION_CODE"
# bing_site_verification: "YOUR_BING_VERIFICATION_CODE"

# If you want to customize or add custom includes, layouts, or data directories:
# include: [".htaccess"]
# exclude: ["node_modules", "vendor", "Gemfile", "Gemfile.lock"]

# End of config
